apiVersion: apps/v1
kind: Deployment
metadata:
  name: geoapi-k8s
spec:
  selector:
    matchLabels:
      app: geoapi-k8s
  replicas: 4
  template:
    metadata:
      labels:
        app: geoapi-k8s
    spec:
      containers:
        - name: geoapi-k8s
          image: mdsami/geoapi-k8s
          ports:
            - containerPort: 3000